build:
  nodes:
    coverage:
      tests:
        override:
          - command: make test
            coverage:
              file: build/coverage.clover   # <- Set this to where we find the coverage data.
                                          #    The path is relative to the current directory.
              format: clover
